### ISSUE TITLE
webspot有集成到crawlab里的计划嘛

### ISSUE THREAD

**Issue by ma-pony** [crawlab-team/webspot#30]

**Comment by tikazyq** [comment]
可以告知一下希望如何集成

**Comment by ma-pony** [comment]
之前看你写过一个可配置爬虫的文章（但crawlab目前好像没有这个功能
https://bbs.huaweicloud.com/blogs/215635

如果webspot集成到crawlab中，是不是可以直接通过webspot勾选生成相应的配置，再生成相应的爬虫，设置定时任务，一个爬虫就写完了

**Comment by ma-pony** [comment]
> 可以告知一下希望如何集成

之前看你写过一个可配置爬虫的文章（但crawlab目前好像没有这个功能
https://bbs.huaweicloud.com/blogs/215635

如果webspot集成到crawlab中，是不是可以直接通过webspot勾选生成相应的配置，再生成相应的爬虫，设置定时任务，一个爬虫就写完了

**Comment by tikazyq** [comment]
现在可以试试示例网站 https://demo.crawlab.cn 中的画布（Canvas），AI 支持功能
